# image will be published to ghcr.io/<user>/<name>
name: izzy-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common-files.yml
  - from-file: common-akmods.yml
  # - from-file: system76-power-packages.yml
  # - from-file: system76-power-systemd.yml
  - from-file: common-rpmfusion-repos.yml
  - from-file: cosmic-desktop-packages.yml
  - from-file: common-packages.yml
  - from-file: common-flatpaks.yml
  - from-file: starship-packages.yml
  - from-file: remove-nvidia-packages.yml
  - from-file: intel-packages.yml
  - from-file: intel-specific.yml
  - from-file: dell-xps-packages.yml
  - from-file: gnome-extensions.yml
  - from-file: gschema-overrides.yml
  - from-file: common-scripts.yml
  - from-file: chezmoi.yml
  - type: signing