# image will be published to ghcr.io/<user>/<name>
name: izzy-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: system-files.yml
  # - from-file: akmods.yml
  # - from-file: evdi.yml
  # - from-file: displaylink-evdi.yml
  # - from-file: displaylink.yml
  - from-file: system76-power.yml
  - from-file: extra-repos.yml
  - from-file: cosmic-desktop.yml
  - from-file: common-packages.yml
  - from-file: common-flatpaks.yml
  - from-file: starship.yml
  - from-file: remove-packages.yml
  - from-file: remove-packages-intel.yml
  - from-file: packages-intel.yml
  - from-file: intel-specific.yml
  - from-file: gnome-extensions.yml
  - from-file: gschema-overrides.yml
  - from-file: scripts.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully