ADD https://negativo17.org/repos/fedora-multimedia.repo /etc/yum.repos.d/fedora-multimedia.repo

RUN --mount=type=cache,target=/var/cache/dnf \
    set -eux; \
    mkdir -p /tmp/displaylink-rpms; \
    dnf5 -y --setopt=install_weak_deps=False install \
    akmods \
    kernel-devel \
    kernel-devel-matched \
    dnf5-plugins && \
    dnf5 download --resolve --destdir /tmp/displaylink-rpms \
    displaylink \
    libevdi \
    xorg-x11-displaylink && \
    rpm -Uvh --nopost --noposttrans /tmp/displaylink-rpms/*.rpm && \
    rm -rf /tmp/displaylink-rpms && \
    dnf5 clean all