ADD https://negativo17.org/repos/fedora-multimedia.repo /etc/yum.repos.d/fedora-multimedia.repo

RUN --mount=type=cache,target=/var/cache/dnf \
    dnf5 -y --setopt=install_weak_deps=False install \
    displaylink \
    kmod-evdi \
    libevdi \
    xorg-x11-server-Xwayland && \
    dnf5 clean all